FROM localhost/container-registry-tools:debian-latest

# Update Sources
RUN apt-get update

# Install required Packages
RUN apt-get install -y python3 python3-pip python3-venv && apt-get clean

# Define Application Path
ARG APP_PATH="/opt/app"

# Define venv Path
ARG VENV_PATH="/opt/venv"

# Create Directories
RUN mkdir -p "${APP_PATH}"

# Copy Sources
COPY app/ "${APP_PATH}"

# Change Directory and Copy requirements.txt
#WORKDIR "/opt"
#COPY requirements.txt requirements.txt

# Create Python venv
RUN python3 -m venv "${VENV_PATH}"

# Set PATH Variable to include venv
ENV PATH="${VENV_PATH}/bin:$PATH"

# Activate venv
RUN source "${VENV_PATH}/bin/activate"
#RUN sh -c ". /opt/venv/bin/activate"

# Install required Packages
RUN pip install --no-cache-dir -r "${APP_PATH}/requirements.txt"

# Set PATH Variable to Include Application
ENV PATH="${APP_PATH}/bin:$PATH"

# Change Directory
WORKDIR "${APP_PATH}"

# Copy and Execute Script for Installation and Initialization of App
COPY docker-entrypoint.sh /opt/
RUN chmod +x /opt/docker-entrypoint.sh
ENTRYPOINT ["/opt/docker-entrypoint.sh"]
